# Generated by Django 4.0a1 on 2021-10-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goali_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
    ]
